// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIt-1ZqkQPfXCs6ojIaKpKyTJRNEaTuTc',
    appId: '1:161733809810:web:3d89a70035f978e328f84b',
    messagingSenderId: '161733809810',
    projectId: 'chatapp-ea532',
    authDomain: 'chatapp-ea532.firebaseapp.com',
    storageBucket: 'chatapp-ea532.appspot.com',
    measurementId: 'G-3MNHSERQQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_oqEKSxu94LcIfUjTcQsdu0zdsGvCAY',
    appId: '1:161733809810:android:5a54067e9e8a5bd628f84b',
    messagingSenderId: '161733809810',
    projectId: 'chatapp-ea532',
    storageBucket: 'chatapp-ea532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqEnbhMyLCSkE1AF4giXdzAvRQvZY5HU',
    appId: '1:161733809810:ios:ab5568f441458e5428f84b',
    messagingSenderId: '161733809810',
    projectId: 'chatapp-ea532',
    storageBucket: 'chatapp-ea532.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqEnbhMyLCSkE1AF4giXdzAvRQvZY5HU',
    appId: '1:161733809810:ios:e61da165cba3ab9b28f84b',
    messagingSenderId: '161733809810',
    projectId: 'chatapp-ea532',
    storageBucket: 'chatapp-ea532.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
